export const projects = [
  {
    title: 'Checkphra Application',
    description: `CheckPhra is my first project. 
    This application is made for people with amulets. Send the image of the amulet to an expert for examination.
    There is a feature to add coins to use to check the amulet and realtime chat with admin.`,
    image: '/images/checkphra-book.PNG',
    tags: ['React-Native', 'Redux-Sagas', 'Firebase'],
    source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
    visit: 'https://project.vipuljha.com/covid/',
    imageList: ['/images/checkphra-img/IMG_1739.jpg', '/images/checkphra-img/IMG_1740.jpg', '/images/checkphra-img/IMG_1741.JPG', '/images/checkphra-img/IMG_1742.jpg',
      '/images/checkphra-img/IMG_1743.jpg', '/images/checkphra-img/IMG_1745.jpg', '/images/checkphra-img/IMG_1747.JPG', '/images/checkphra-img/IMG_1748.JPG', '/images/checkphra-img/IMG_1752.JPG'],
    id: 0,
  },
  {
    title: 'Hino Connect Web',
    description: `This website is for managing and observing vehicles.
    All hino cars are equipped with gps and sensors.
    Can see the current coordinates of each car, including acceleration, speed, braking and other details.`,
    image: '/images/hino-booking.png',
    tags: ['React JS', 'CSS', 'Bootstrap', 'Redux-Sagas'],
    source: 'https://github.com/teachdugsimt/website',
    visit: 'https://project.vipuljha.com/website/',
    imageList: ['/images/hino-img/hino1.png', '/images/hino-img/hino2.png', '/images/hino-img/hino3.png', '/images/hino-img/hino4.png'],
    id: 1,
  },
  {
    title: 'TCRB backoffice',
    description: "This website is built to audit internal transactions. It has the following features: generate report as excel files, set roles and permission, register partner for business, audit log for any actions, approve - reject any actions.",
    image: '/images/tcrb-booking.PNG',
    tags: ['NextJS', 'Mobx', 'NodeJS', 'AWS'],
    source: 'https://github.com/teachdugsimt/ABS-Tweaks',
    visit: 'https://forum.xda-developers.com/t/tweak-mod-arm-x86-project-dark-booster-abs-tweaks-v5-0-2-3-6-0-23-01-2016.3120404/',
    imageList: ['/images/tcrb-img/tcrb-login.PNG', '/images/tcrb-img/cust-service-enquiry.png', '/images/tcrb-img/partner-management.png',
      '/images/tcrb-img/partner-management2.png', '/images/tcrb-img/partner-management3.png', '/images/tcrb-img/partner-management4.png',
      '/images/tcrb-img/partner-management5.png', '/images/tcrb-img/pending-approve.png', '/images/tcrb-img/product-management.png',
      '/images/tcrb-img/partner-management2.png', '/images/tcrb-img/report1.png', '/images/tcrb-img/role-matrix.png'],
    id: 2,
  },
  {
    title: 'Cargolink',
    description: "Cargolink is a transport matching service under the concept of Sharing Economy by reusing empty car loads to use together. To make transportation in Thailand more efficient reduce transportation costs increase return income.",
    image: '/images/cargolink-booking.png',
    tags: ['React-Native', 'Mobx', 'Fastify', 'AWS', 'Gatsby', 'LineDev'],
    source: 'https://github.com/teachdugsimt/electrablue_mido',
    visit: 'https://forum.xda-developers.com/t/kernel-mido-oreo-pie-electrablue-kernel-21-0-july-06-redmi-note-4.3655651/',
    imageList: ['/images/cargo-img/cargo1.png', '/images/cargo-img/cargo2.png', '/images/cargo-img/cargo3.png', '/images/cargo-img/cargo4.png',
      '/images/cargo-img/cargo5.png', '/images/cargo-img/cargo6.png', '/images/cargo-img/cargo7.png', '/images/cargo-img/cargo8.png',
      '/images/cargo-img/cargo9.png', '/images/cargo-img/cargo10.png', '/images/cargo-img/cargo11.png', '/images/cargo-img/cargo12.png',
      '/images/cargo-img/cargo13.png', '/images/cargo-img/cargo14.png', '/images/cargo-img/cargo15.png', '/images/cargo-img/cargo16.png',
      '/images/cargo-img/cargo17.png', '/images/cargo-img/cargo18.png', '/images/cargo-img/cargo19.png', '/images/cargo-img/cargo20.png',],
    id: 3,
  },
  {
    title: 'PSP (SCGC)',
    description: "PSP is a web site for users to manage production schedules for various materials. On the web there is also a permission management system.",
    image: '/images/psp-booking.png',
    tags: ['React', 'Spring Boot', 'MS-SQL'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/app-port-6-0-lenovo-snapit-camera-5-8-53-for-all-devices.3608065/',
    imageList: ['/images/psp/psp1.png', '/images/psp/psp2.png', '/images/psp/psp3.png'],
    id: 4,
  },
  {
    title: 'Tracking Project',
    description: "Tracking project is website for management internal project. It can save any details or document. There are reports that any project is undocumented. You can see overview timeline for each project. This website also including roles and permissions.",
    image: '/images/tracking-booking.png',
    tags: ['React', 'UmiJS', 'NestJS', 'MongoDB'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    imageList: ['/images/tracking-img/tracking2.png', '/images/tracking-img/tracking3.png', '/images/tracking-img/tracking4.png',
      '/images/tracking-img/tracking5.png', '/images/tracking-img/tracking6.png', '/images/tracking-img/tracking7.png',
      '/images/tracking-img/tracking8.png', '/images/tracking-img/tracking9.png',],
    id: 5,
  },
  {
    title: 'Tracking Project',
    description: "Tracking project is website for management internal project. It can save any details or document. There are reports that any project is undocumented. You can see overview timeline for each project. This website also including roles and permissions.",
    image: '/images/tracking-booking.png',
    tags: ['React', 'UmiJS', 'NestJS', 'MongoDB'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    imageList: ['/images/tracking-img/tracking2.png', '/images/tracking-img/tracking3.png', '/images/tracking-img/tracking4.png',
      '/images/tracking-img/tracking5.png', '/images/tracking-img/tracking6.png', '/images/tracking-img/tracking7.png',
      '/images/tracking-img/tracking8.png', '/images/tracking-img/tracking9.png',],
    id: 5,
  },
  {
    title: 'Resource Management',
    description: "Resource management is website for store information of people in the organization. It can save any infomation or documents. Can display reports about salary and experience.",
    image: '/images/resource-booking.png',
    tags: ['React', 'Azure', 'NestJS', 'MongoDB'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    imageList: ['/images/resource-img/resource1.png', '/images/resource-img/resource2.png', '/images/resource-img/resource3.png'],
    id: 6,
  },
  {
    title: 'SSO App Admin',
    description: "App admin is website for manages various settings for each application in the organization. Can create applications and define environments for development. Including page creation with path and role assignment.",
    image: '/images/app-admin-booking.png',
    tags: ['React', 'Azure', 'ExpressJS', 'MongoDB'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    imageList: ['/images/app-admin/app-admin1.png', '/images/app-admin/app-admin2.png', '/images/app-admin/app-admin3.png', '/images/app-admin/app-admin4.png',
      '/images/app-admin/app-admin5.png', '/images/app-admin/app-admin6.png'],
    id: 7,
  },
  {
    title: 'Status booking web',
    description: "Status booking is website for booking status bar ticket. There is a calendar to show dates and events. Users can provide a few details, then select the desired event and make a booking and payment.",
    image: '/images/status-booking.png',
    tags: ['Next JS', 'AWS', 'NestJS', 'MongoDB'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    imageList: ['/images/status-booking/status-booking1.png', '/images/status-booking/status-booking2.png', '/images/status-booking/status-booking3.png', '/images/status-booking/status-booking4.png',
      '/images/status-booking/status-booking5.png'],
    id: 8,
  },
  {
    title: 'Status CRM web',
    description: "Status crm is website for management event and master table plan in store. There is a system for creating tables and using the created tables to create table plans. There is a system for creating and assigning events to each day in the calendar.",
    image: '/images/status-crm-booking.png',
    tags: ['Next JS', 'AWS', 'NestJS', 'MongoDB'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    imageList: ['/images/status-crm/status-crm1.png', '/images/status-crm/status-crm2.png', '/images/status-crm/status-crm3.png', '/images/status-crm/status-crm4.png',
      '/images/status-crm/status-crm5.png', '/images/status-crm/status-crm6.png', '/images/status-crm/status-crm7.png'],
    id: 8,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Worked intensively on React-Native & Firebase.', },
  { year: 2018, text: 'Have the opportunity to create a website using React.', },
  { year: 2019, text: 'Starting with nodeJS api and practice to use AWS service.', },
  { year: 2020, text: 'Complete challenging project with heavy work, mainly frontend with NextJS.', },
  { year: 2021, text: 'Began to practice designing databases and doing AWS infrastructure. Also including frontend.', },
  { year: 2022, text: 'Work with SCGC as Full Stack Developer.Try new stack like Angular, Spring Boot.', },
  { year: 2023, text: 'Try out Azure services like Azure DevOps, App Service, CosmosDB.', },
  { year: 2024, text: 'Design infrastructure of project based on container app. Some apps use serverless.', },
  { year: 2025, text: 'Still working till now.', },
];